[package]
name = "shapley"
version = "0.1.0"
edition = "2024"

[lib]
name = "lib"
path = "src/lib.rs"

[dependencies]
itertools = "0.14.0"
thiserror = "2.0.12"
rayon = "1.10.0"

[profile.release]
debug = true
